try {
  a = b + c;
} catch (error) {
  console.log(error);
  console.log("teste");
} finally{
  console.log("concluido");
}